# Generated by Django 4.2.5 on 2023-10-03 01:50
# Generated by Django 4.2.5 on 2023-10-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_user',
            fields=[
                ('userId', models.CharField(max_length=255)),
                ('autoId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
                ],
            ),

       
    ]
