# Generated by Django 4.2.5 on 2023-10-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='temp',
            field=models.CharField(default='r', max_length=22),
            preserve_default=False,
        ),
    ]
