# Generated by Django 4.2.5 on 2023-09-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='id_beca',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
