# Generated by Django 4.2.5 on 2023-10-03 23:32

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, serialize=False, verbose_name='ID')),
                ('auto_id', models.CharField(default=uuid.uuid4, editable=False ,primary_key=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.IntegerField()),
                ('type_scholarship', models.CharField(max_length=50)),
            ],
        ),
    ]