# Generated by Django 4.2.5 on 2023-10-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0002_scholarship_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
