# Generated by Django 4.2.5 on 2023-11-14 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0002_typescholarship_units_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typescholarship',
            old_name='weight_percentaje',
            new_name='weight_percentage',
        ),
    ]
