# Generated by Django 4.2.5 on 2023-09-27 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0002_alter_calendar_inscription_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='selection_start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
