# Generated by Django 4.2.5 on 2023-10-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0003_typescholarship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='name',
        ),
    ]
