# Generated by Django 4.2.5 on 2023-09-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0003_calendar_selection_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='selection_start_date',
            field=models.DateField(),
        ),
    ]
