# Generated by Django 4.2.5 on 2023-11-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0003_rename_weight_percentaje_typescholarship_weight_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='types',
            field=models.ManyToManyField(to='app_becas.typescholarship'),
        ),
    ]
