# Generated by Django 4.2.5 on 2023-10-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
