# Generated by Django 4.2.5 on 2023-10-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='name',
        ),
    ]
