# Generated by Django 4.2.5 on 2023-11-16 01:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0004_scholarship_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipParams',
            fields=[
                ('auto_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type_name', models.CharField(default=uuid.uuid4, max_length=30)),
                ('scholarship_id', models.CharField(default=uuid.uuid4, max_length=30)),
                ('units', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('units_type', models.CharField(default=1, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='type_scholarship',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='types',
        ),
        migrations.RemoveField(
            model_name='typescholarship',
            name='units_available',
        ),
        migrations.RemoveField(
            model_name='typescholarship',
            name='units_type',
        ),
        migrations.RemoveField(
            model_name='typescholarship',
            name='weight_percentage',
        ),
    ]
