# Generated by Django 4.2.5 on 2023-10-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0004_remove_scholarship_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='name',
            field=models.CharField(default='hola', max_length=30),
            preserve_default=False,
        ),
    ]
