# Generated by Django 4.2.5 on 2023-10-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0005_scholarship_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholarship',
        ),
    ]
