# Generated by Django 4.2.5 on 2023-10-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_becas', '0007_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typescholarship',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
